spring:
  application.name: query-mapper
  # H2 Database ??
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'   # H2 DB ?? ?? (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
    username: sa        # H2 DB ?? ID (??? ??)
    password:        # H2 DB ?? PW (??? ??)

  # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console       # H2 Console ?? ??

mybatis.config-location: classpath:mybatis-config.xml